### ISSUE TITLE
Match ncores() and length of cores() ?

### ISSUE THREAD

**Issue by oschulz** [carstenbauer/SysInfo.jl#11]
This is probably confusing for users:

```julia
julia> sysinfo()
Hostname:       ...
CPU(s):         1 x 13th Gen Intel(R) Core(TM) i9-13900H
CPU target:     goldmont

∘ CPU 1: 
        → 14 cores (20 CPU-threads due to 2-way SMT)
        → 8 "efficiency cores", 6 "performance cores".
        → 1 NUMA domain

julia> ncores(), length(cores())
(14, 20)
```

Is this due to the mix if cores with and without HT in this CPU?

**Comment by oschulz** [comment]
I was trying to do

```
filter(i -> !isefficiencycore(i) && !ishyperthread(i), sort(cores()))
```

which works, currently - but I guess using `cores()` here is wrong, at least for `ishyperthread`, semantically?

I guess that should be

```
filter(i -> !isefficiencycore(i) && !ishyperthread(i), sort(SysInfo.cpuids()))
```

(is `SysInfo.cpuids` part of the stable API?)

**Comment by carstenbauer** [comment]
> Is this due to the mix if cores with and without HT in this CPU?

No. The function `cores` behaves according to [its documentation](https://carstenbauer.github.io/ThreadPinning.jl/stable/refs/api_querying/#ThreadPinning.cores). All of the [logical querying functions](https://carstenbauer.github.io/ThreadPinning.jl/stable/refs/api_querying/#api_logical) return IDs of CPU-threads.

These functions are mostly supposed to be used in conjuction with `pinthread`/`pinthreads`. And you can only pin to CPU-threads (i.e. CPU IDs). Thus, CPU-threads is what you work with, not CPU-cores.


> (is `SysInfo.cpuids` part of the stable API?)

No, it's not (as indicated by the fact that it is neither `exported` nor marked as `@public`). You never need it though. The logical accessor functions are strictly better because they give you a deterministic logical order that you can rely on. For example, like `SysInfo.cpuids()`,`node()` gives you all CPU-thread IDs of the system but ordered such that hyperthreads are guaranteed to come after the first CPU-threads in each core. Try it out and compare with `node(; compact=true)`.

> I was trying to do
> 
> ```
> filter(i -> !isefficiencycore(i) && !ishyperthread(i), sort(cores()))
> ```
> 
> which works, currently - but I guess using `cores()` here is wrong, at least for `ishyperthread`, semantically?

The name of the function `isefficiencycore` is misleading here. I will change it to `isinefficiencycore` or similar. Almost all functions take in logical or OS indices of CPU-threads. Almost none of them takes a logical core ID (from the top of my head, `core` (singular) is the only exception).

Besides the misleading name `isefficiencycore`, your code line is semantically fine. It is questionable though: `cores()` gives you all CPU-thread IDs of the system in a specific order (see docstring). Why would you call `sort` on it? That makes little sense, because ordering by CPU-thread IDs is "non-deterministic" in the sense that you have no idea what order you get logically (because CPU-thread IDs can be arbitrary, although they often aren't on most systems).

The `!ishyperthread` part is also redundant if you use the logical accessor functions appropriately. As mentioned above, their output has a certain logical order so you can just do `node(1:ncores())`. Hence, something like

```
filter(!isefficiencycore, node(1:ncores()))
```
would be enough.

Finally, let me say that you - very likely - shouldn't use SysInfo directly but should use the re-exported functions of ThreadPinning.

**Comment by carstenbauer** [comment]
While I agree that `ncores(), length(cores())` is a bit misleading, it makes sense and is consistent with other functions the way it is. I'm therefore inclined to close this issue.

(If anything, dropping the `cores` function altogether might be a good idea because it is an alias for `node(; compact=false)`.)

**Comment by oschulz** [comment]
Thanks for the explanations! I'll close this, then.

> Why would you call sort on it

That was just because I wanted to use it for Julia and OpenBLAS thread pinning in order afterwards - but you're right, after separating into "hyperthreads" and "non-hyperthreads" they would have been in order anyway. :-)

And yes, I'll use ThreadPinning directly in the future as recommended.
